In [4]:
import sys
import os
import numpy as np
import time

# 현재 파일(main.ipynb)이 있는 디렉토리의 부모 디렉토리를 sys.path에 추가
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))

In [72]:
from main.config import *
from state.ver2 import *

In [7]:
State = select_state(3)

In [73]:
state = State()
s = state()

In [16]:
s[0,1,:] = 1
s[1,2,:] = 1
s

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1

In [14]:
def rotate_90(state):
    return np.rot90(state, k=-1, axes=(1, 2))  # 90도 시계 방향 회전

In [17]:
rotate_90(s)

array([[[0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0.]],

       [[0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1

In [25]:
def rotate_90(state):
    '''
    90 degree 시계 방향 회전 
    '''
    return np.rot90(state, k=-1, axes=(1, 2))  # 90도 시계 방향 회전

def rotate_180(state):
    '''
    180 degree 시계 방향 회전 
    '''
    return np.rot90(state, k=-2, axes=(1, 2))  # 180도 회전

def rotate_270(state):
    '''
    270 degree 시계 방향 회전 
    '''
    return np.rot90(state, k=-3, axes=(1, 2))  # 270도 회전

def flip_vertical(state):
    '''
    상하 반사  
    '''
    return np.flip(state, axis=1)  # 상하 반사

def flip_horizontal(state):
    '''
    좌우 반사
    '''
    return np.flip(state, axis=2)  # 좌우 반사

def flip_diagonal_main(state):
    '''
    주대각선 (\) 반사 
    '''
    return np.transpose(state, axes=(0, 2, 1))  # 주대각선 (\) 반사

def flip_diagonal_anti(state):
    '''
    반대 대각선 (/) 반사 
    '''
    return np.flip(np.transpose(state, axes=(0, 2, 1)), axis=2)  # 반대 대각선 (/) 반사

def generate_batch(state):
    symmetries = np.stack([
        state,
        rotate_90(state),
        rotate_180(state),
        rotate_270(state),
        flip_vertical(state),
        flip_horizontal(state),
        flip_diagonal_main(state),
        flip_diagonal_anti(state)
    ], axis=0)
    return symmetries


state = np.arange(2 * 3 * 3).reshape(2, 3, 3)

# 변형된 보드 상태 출력
symmetries = generate_symmetries(state)
print(symmetries.shape)
# for i, sym_board in enumerate(symmetries):
#     print(f"Transformation {i+1}:")
#     print(sym_board, "\n")


(8, 2, 3, 3)


In [19]:
def flip_vertical(state):
    return np.flip(state, axis=1)  # 상하 반사

def flip_horizontal(state):
    return np.flip(state, axis=2)  # 좌우 반사

def flip_diagonal_main(state):
    return np.transpose(state, axes=(0, 2, 1))  # 주대각선 (\) 반사

def flip_diagonal_anti(state):
    return np.flip(np.transpose(state, axes=(0, 2, 1)), axis=2)  # 반대 대각선 (/) 반사

# 테스트용 샘플 state (5, 9*9)를 (5, 9, 9) 형태로 변환
state = np.arange(5 * 9 * 9).reshape(5, 9, 9)

# 변형 적용
state_v = flip_vertical(state)
state_h = flip_horizontal(state)
state_d1 = flip_diagonal_main(state)
state_d2 = flip_diagonal_anti(state)

# 결과 출력
print("Original State:\n", state.shape)  # 첫 번째 채널 출력
print("\nFlipped Vertical:\n", state_v.shape)
print("\nFlipped Horizontal:\n", state_h.shape)
print("\nFlipped Diagonal (Main \\):\n", state_d1.shape)
print("\nFlipped Diagonal (Anti /):\n", state_d2.shape)

Original State:
 (5, 9, 9)

Flipped Vertical:
 (5, 9, 9)

Flipped Horizontal:
 (5, 9, 9)

Flipped Diagonal (Main \):
 (5, 9, 9)

Flipped Diagonal (Anti /):
 (5, 9, 9)


In [26]:
import random

In [32]:
np.random.choice(8)

2

In [33]:
def rotate_90(state):
    '''
    90 degree 시계 방향 회전 
    '''
    return np.rot90(state, k=-1, axes=(1, 2)) 

def rotate_180(state):
    '''
    180 degree 시계 방향 회전 
    '''
    return np.rot90(state, k=-2, axes=(1, 2)) 

In [34]:
def select():
    return (rotate_90, rotate_180)

In [35]:
ftn1, ftn2 = select()

In [36]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [41]:
np.random.randint(0,8,size=(8))

array([4, 2, 0, 7, 0, 5, 3, 6])

In [42]:
from utils.transpose_state import *

In [51]:
def get_dihedral_transpose_ftns(idx : int):
    '''
    get_dihedral_transpose_ftns(idx : int) -> [ftn(state / policy), inverse_ftn(state / policy)]
    state / policy 's shape : (-1, *STATE_SHAPE)
    '''
    if idx == 0:
        return (get_original, get_original)
    
    elif idx == 1:
        return (rotate_90, inverse_rotate_90)
    
    elif idx == 2:
        return (rotate_180, inverse_rotate_180)
    
    elif idx == 3:
        return (rotate_270, inverse_rotate_270)
    
    elif idx == 4:
        return (flip_vertical, inverse_flip_vertical)
    
    elif idx == 5:
        return (flip_horizontal, inverse_flip_horizontal)
    
    elif idx == 6:
        return (flip_diagonal_main, inverse_flip_diagonal_main)
    
    elif idx == 7:
        return (flip_diagonal_anti, inverse_flip_diagonal_anti)

In [64]:
indices = np.random.randint(0,8,size=(8))
ftn_lst = list(zip(*map(lambda idx: get_dihedral_transpose_ftns(idx), indices)))
ftn_lst

[(<function utils.transpose_state.flip_horizontal(board)>,
  <function utils.transpose_state.rotate_180(board)>,
  <function utils.transpose_state.get_original(board)>,
  <function utils.transpose_state.get_original(board)>,
  <function utils.transpose_state.rotate_180(board)>,
  <function utils.transpose_state.rotate_180(board)>,
  <function utils.transpose_state.rotate_270(board)>,
  <function utils.transpose_state.flip_diagonal_main(board)>),
 (<function utils.transpose_state.inverse_flip_horizontal(board)>,
  <function utils.transpose_state.inverse_rotate_180(board)>,
  <function utils.transpose_state.get_original(board)>,
  <function utils.transpose_state.get_original(board)>,
  <function utils.transpose_state.inverse_rotate_180(board)>,
  <function utils.transpose_state.inverse_rotate_180(board)>,
  <function utils.transpose_state.inverse_rotate_270(board)>,
  <function utils.transpose_state.inverse_flip_diagonal_main(board)>)]

In [65]:
import numpy as np
import time

indices = np.random.randint(0, 8, size=1000000)

# 기존 코드 (map + zip)
start = time.time()
ftn_lst1 = list(zip(*map(lambda idx: get_dihedral_transpose_ftns(idx), indices)))
end = time.time()
print(f"Original (map): {end - start:.6f} sec")

# 최적화 코드 (list comprehension + zip)
start = time.time()
ftn_lst2 = tuple(zip(*[get_dihedral_transpose_ftns(idx) for idx in indices]))
end = time.time()
print(f"Optimized (list comprehension): {end - start:.6f} sec")

Original (map): 0.823190 sec
Optimized (list comprehension): 0.538448 sec


In [58]:
ftns = list(zip(*ftn_lst))

In [67]:
s = State()

In [61]:
states = [s(),s(),s(),s(), s(),s(),s(),s()]

In [66]:
results = list(map(lambda x_f: x_f[1](x_f[0]), zip(states, ftns[0])))

In [69]:
indices = np.random.randint(0,81,size=100)

In [76]:
ss = list(map(lambda action: state.next(action)(),indices))

In [81]:
np.stack(list(map(lambda x_f: x_f[1](x_f[0]), zip(ss, ftns[0]))), axis=0)

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]],


       [[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0.

In [84]:
random.choice(range(8))

6

In [85]:
rotate_ftns = [rotate_90, rotate_180, rotate_270, 
               flip_vertical, flip_horizontal, 
               flip_diagonal_main, flip_diagonal_anti]

In [86]:
s = state()

In [87]:
[ft(s) for ft in rotate_ftns]

[array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
        [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       